#New yusuf


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  mavenGoal: "clean install"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      buildScript: "pom.xml"
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: "mvn -B ${mavenGoal} --file ${buildScript}"
    - uses: actions/upload-artifact@v3
      with:
       name: buildArtifact
       path: target/*.war      
