deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: buildArtifact

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.imageName }}:${{ env.imageTag }} .
        echo ${{ secrets.DOCKER_TOKEN }} | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ env.imageName }}:${{ env.imageTag }}
