#New yusuf


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  mavenGoal: "clean install"
  imageName: "yusuf-springboot-mavent"
  imageTag: "v1"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      buildScript: "pom.xml"
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: "mvn -B ${mavenGoal} --file ${buildScript}"
    - uses: actions/upload-artifact@v3
      with:
       name: buildArtifact
       path: target/*.war      

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: buildArtifact

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      with:
        context: .
      run: |
        docker build -t ${{ env.imageName }}:${{ env.imageTag }} .
        echo ${{ secrets.DOCKER_TOKEN }} | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ env.imageName }}:${{ env.imageTag }}
